---
- name: Create main Postgres configuration
  template:
    src: postgresql.conf.j2
    dest: "{{ conf_directory }}/postgresql.conf"
    owner: root
    group: "{{ postgres_group }}"
    mode: 0640

- name: Create host-based auth config
  template:
    src: pg_hba.conf.j2
    dest: "{{ conf_directory }}/pg_hba.conf"
    mode: 0640
    owner: root
    group: "{{ postgres_group }}"
  notify: Reload postgresql

- name: Create identity-mapping file
  template:
    src: pg_ident.conf.j2
    dest: "{{ conf_directory }}/pg_ident.conf"
    mode: 0640
    owner: root
    group: "{{ postgres_group }}"
  notify: Reload postgresql

- name: Create service file
  template:
    src: pg_service.conf.j2
    dest: "/etc/pg_service.conf"
    mode: 0644
    owner: root
    group: "root"

- name: Tell psql to use correct socket location
  template:
    src: profile.sh.j2
    dest: "{{ item }}"
    owner: root
    group: root
    mode: 0755
  with_items:
    - /etc/profile.d/postgresql.sh
    - "{{ data_directory }}/.profile"
    - "{{ data_directory }}/.bashrc"

- name: Stat Postgres version
  stat:
    path: "{{ data_directory }}/PG_VERSION"
  register: postgres_version

# Using sudo because become_user may be overridden
- name: Initialize database
  command: sudo -Hu {{ postgres_user }} initdb --locale {{ locale }} -E {{ encoding }} -D {{ data_directory }}
  when: not postgres_version.stat.exists

- name: Include Postgres config
  template:
    src: postgresql_include.conf.j2
    dest: "{{ data_directory }}/postgresql.conf"
    mode: 0640
    owner: root
    group: "{{ postgres_group }}"

- name: Create unit file
  template:
    src: postgresql.service.j2
    dest: /etc/systemd/system/postgresql.service
    mode: 0644
    owner: root
    group: root
  register: unitfile

- name: Reload systemd
  command: systemctl daemon-reload
  when: unitfile.changed

- name: Enable and start
  service:
    name: postgresql.service
    state: running
    enabled: yes
  when: not unitfile.changed

- name: Enable and restart
  service:
    name: postgresql.service
    state: restarted
    enabled: yes
  when: unitfile.changed
